### ISSUE TITLE
C++17 fixes not merged to master

### ISSUE THREAD

**Issue by pdimov** [boostorg/locale#23]
The commit

https://github.com/boostorg/locale/commit/322437a485c63d9fce4dc620597b6c75b6396daf

that enables compilation on C++17 has not been applied to master. It's too late for the 1.66 beta, but perhaps it needs to be applied for the 1.66 release once master is open for changes?

**Comment by artyom-beilis** [comment]
Ok good point

**Comment by pdimov** [comment]
`master` still doesn't build on C++17.

**Comment by artyom-beilis** [comment]
Merged all changes in develop to master.

Now should be fixed
