### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by abdes** [boostorg/locale#25]
In ``https://github.com/boostorg/locale/blob/develop/src/win32/lcid.cpp``

use of boost::unique_lock without including <boost/thread/lock_types.hpp> makes the compilation fail.

Visual Studio 2017
boost::locale latest (boost 1.67.0)

**Comment by lc-Arvin** [comment]
actually https://github.com/boostorg/locale/pull/30/commits will fix this this issue.

**Comment by Flamefire** [comment]
Fixed by #85
