### ISSUE TITLE
Regex Fails when locale from boost on clang 6 and libc++

### ISSUE THREAD

**Issue by schorsch1976** [boostorg/locale#35]
On FreeBSD 11.2 + 12.0 amd64 and boost 1.68.0 This fails: On all other tested platforms it matches ok. FreeBSD maintainer said, that it might be a bug in boost::locale.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233994

[bug.txt](https://github.com/boostorg/locale/files/2686566/bug.txt)

**Comment by artyom-beilis** [comment]
Boost.Regex and Boost.Locale aren't related, the locale generated by Boost.Locale is "C" locale with addons unrelated to Boost.Regex

**Comment by schorsch1976** [comment]
The bug triggers NOT with boost::regex, it triggers only JUST on FreeBSD when i use a boost:locale and std::regex from libc++.

**Comment by artyom-beilis** [comment]
How do yo use std::regex with and without std::locale/boost::locale

**Comment by schorsch1976** [comment]
Yes, exactly: It just triggers with std::regex from libc++ and clang on FreeBSD. With a locale from std(libc++) it matches all ok. It just fails with std::regex(libc++) and a locale from boost. (1.68.0). Please see the attached bug.txt.

**Comment by artyom-beilis** [comment]
What std::locale from libstdc++? Show sample with std::locale.

**Comment by schorsch1976** [comment]
`// build with
// clang --std=c++17 bug.cpp -O0 -g  -I /usr/local/include -lc++ -L/usr/local/lib/ -lboost_locale
// freebsd-version  11.2-RELEASE-p1
// clang FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)

#include <regex>
#include <string>
#include <iostream>

#include <boost/locale.hpp>

int main(int argc, char** argv)
{
	boost::locale::generator gen;
	std::locale loc{ gen("de_DE.UTF-8") };
	std::locale::global(loc);
		
	std::string test {{
	"Date: 2018-12-09 14:40:27" }};

	std::regex re_datetime("^Date\\s*:[\\s\\t]*(\\d{4}\\-\\d{2}\\-\\d{2} "
							"\\d{2}:\\d{2}:\\d{2}?)$",
							std::regex_constants::icase);

	std::smatch match;

	if (std::regex_match(test, match, re_datetime) && match.size() > 1)
	{
		std::cout << "All ok" << std::endl;
	}
	else
	{
		std::cout << "Bug triggered" << std::endl;
	}
}
`

**Comment by artyom-beilis** [comment]
And how it behaves when you don't set std::locale::global?

**Comment by schorsch1976** [comment]
If i use "std::locale log("de_DE.UTF-8")" it works. 
If i dont set the global locale, it works too. It just fails with the global locale from boost.

**Comment by artyom-beilis** [comment]
what happens if you set `std::locale log=std::locale::classic()` ?

**Comment by schorsch1976** [comment]
#include <regex>
#include <string>
#include <iostream>

#include <boost/locale.hpp>

int main(int argc, char** argv)
{
        boost::locale::generator gen;
        std::locale loc=std::locale::classic();
        //std::locale loc{ gen("de_DE.UTF-8") };
        std::locale::global(loc);

        std::string test {{
        "Date: 2018-12-09 14:40:27" }};

        std::regex re_datetime("^Date\\s*:[\\s\\t]*(\\d{4}\\-\\d{2}\\-\\d{2} "
                                                        "\\d{2}:\\d{2}:\\d{2}?)$",
                                                        std::regex_constants::icase);

        std::smatch match;

        if (std::regex_match(test, match, re_datetime) && match.size() > 1)
        {
                std::cout << "All ok" << std::endl;
        }
        else
        {
                std::cout << "Bug triggered" << std::endl;
        }
}










➜  ~ clang --std=c++17 bug.cpp -O0 -g  -I /usr/local/include -lc++ -L/usr/local/lib/ -lboost_locale && ./a.out
bug.cpp:19:20: warning: braces around scalar initializer [-Wbraced-scalar-init]
        std::string test {{
                          ^
1 warning generated.
All ok
➜  ~

**Comment by schorsch1976** [comment]
As expected: "All ok".

**Comment by schorsch1976** [comment]
I used the precompiled boost from freebsd. ICU is the backend.

PORTNAME=       boost-libs
PORTREVISION=   1

COMMENT=        Free portable C++ libraries (without Boost.Python)

BROKEN_sparc64= https://github.com/boostorg/context/commit/f2ef6326b6ed

BUILD_DEPENDS+= bjam:devel/boost-jam

# libs/config/test/boost_no_cxx11_thread_local.ipp fails (see base r303795)
PLIST_SUB+=     FIBER="${"${OPSYS}"=="FreeBSD" && ${OSREL:R} < 11:?@comment :}"

OPTIONS_DEFINE=         DEBUG OPTIMIZED_CFLAGS
OPTIONS_MULTI=          LOCALE
OPTIONS_MULTI_LOCALE=   ICONV ICU
OPTIONS_DEFAULT=        ICONV ICU
ICONV_DESC=             Boost.Locale with iconv encoding support
ICU_DESC=               Boost.Regex/Locale with ICU unicode support

ICONV_USES=             iconv
ICONV_MAKE_ARGS=        -sICONV_PATH=${ICONV_PREFIX}
ICONV_MAKE_ARGS_OFF=    boost.locale.iconv=off
ICU_LIB_DEPENDS=        libicuuc.so:devel/icu
ICU_MAKE_ARGS=          -sICU_PATH=${LOCALBASE}
ICU_MAKE_ARGS_OFF=      boost.locale.icu=off

.include "${.CURDIR}/../boost-all/common.mk"

**Comment by schorsch1976** [comment]
dd /usr/local/lib/libboost_locale.so 
/usr/local/lib/libboost_locale.so:
        libboost_chrono.so.1.68.0 => /usr/local/lib/libboost_chrono.so.1.68.0 (0x80074f000)
        libboost_thread.so.1.68.0 => /usr/local/lib/libboost_thread.so.1.68.0 (0x800757000)
        libboost_system.so.1.68.0 => /usr/local/lib/libboost_system.so.1.68.0 (0x800778000)
        libicudata.so.62 => /usr/local/lib/libicudata.so.62 (0x80077f000)
        libicui18n.so.62 => /usr/local/lib/libicui18n.so.62 (0x800e00000)
        libicuuc.so.62 => /usr/local/lib/libicuuc.so.62 (0x8010fb000)
        libc++.so.1 => /usr/lib/libc++.so.1 (0x8012d4000)
        libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x800781000)
        libm.so.5 => /lib/libm.so.5 (0x8007a2000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x8007d4000)
        libthr.so.3 => /lib/libthr.so.3 (0x8013a3000)
        libc.so.7 => /lib/libc.so.7 (0x800248000)
        librt.so.1 => /usr/lib/librt.so.1 (0x8007ec000)

**Comment by artyom-beilis** [comment]
What happens if you don't use icase?

**Comment by artyom-beilis** [comment]
And what happens if you try to use other backends: like posix or std

https://www.boost.org/doc/libs/1_50_0/libs/locale/doc/html/using_localization_backends.html

**Comment by artyom-beilis** [comment]
Also it would help if you can figure out what type of facets generates problem:

List of categories:

https://www.boost.org/doc/libs/1_50_0/libs/locale/doc/html/namespaceboost_1_1locale.html#a980b72231e52c32b8bef91ce60e6936a

How to set them
https://www.boost.org/doc/libs/1_50_0/libs/locale/doc/html/classboost_1_1locale_1_1generator.html#ae3c095f074329954eb90bb80488c7f76

**Comment by schorsch1976** [comment]
Without icase, the tesult is "All ok"

**Comment by schorsch1976** [comment]
I tried all facets and it triggers at "all_characters , collation_facet, all_categories ""

Updated testcase:
[bug.txt](https://github.com/boostorg/locale/files/2687111/bug.txt)

**Comment by schorsch1976** [comment]
I ran 13824 testcases.
192 locales (1 segfaults if i do it) x 3 backends x 12 facets x icase on/off. 

[bug.txt](https://github.com/boostorg/locale/files/2689429/bug.txt)
[result-csv.txt](https://github.com/boostorg/locale/files/2689430/result-csv.txt)

If you import the csv into excel/libreoffice you can see that the bug triggers very often. As far as i have analyzed it, its always 
"all_characters , collation_facet, all_categories".

**Comment by schorsch1976** [comment]
C and POSIX work always ok.

**Comment by schorsch1976** [comment]
Pivot analysis of the result table shows, "all_characters , collation_facet, all_categories". C and POSIX work always ok. Every locale is affected: Even en_US.UTF-8.


[result-csv.ods.tar.gz](https://github.com/boostorg/locale/files/2689615/result-csv.ods.tar.gz)

**Comment by Lord-Kamina** [comment]
Hello. I am experiencing a similar issue on macOS Ventura:

With Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin22.6.0.

The following code:

```c++
#include <boost/locale.hpp>
#include <iostream>
#include <locale>
#include <regex>
#include <string>

int main() {
	boost::locale::generator locGen;
	const std::locale loc = locGen("en_US.UTF-8");
// 	std::locale::global(loc);  
	auto pattern = std::regex(R"(^(?:\s)*([_[:alnum:].-]+)\s*=\s*([^;#\n\r]+)*)");
// 	pattern.imbue(loc);
	const std::string text{"  pozo = mani"};
	std::smatch result;
	std::regex_search(text, result, pattern);
	std::cout << "ready: " << result.ready() << ", size: " << result.size() << std::endl;
	for (size_t i=0; i < result.size(); i++) {
		std::cout << "match[" <<i<<"]: " << result[i] <<std::endl;
	}
	return 0;
}
```

```bash
$ clang++ -o regex_test regex_test.cpp -std=c++17 -I/opt/local/include/ -lboost_locale-mt -lboost_system-mt -L/opt/local/lib && ./regex_test
ready: 1, size: 3
match[0]:   pozo = mani
match[1]: pozo
match[2]: mani
```

If I uncomment the `std::locale::global` line (with or without the `pattern.imbue`):

```bash
clang++ -o regex_test regex_test.cpp -std=c++17 -I/opt/local/include/ -lboost_locale-mt -lboost_system-mt -L/opt/local/lib && ./regex_test
ready: 1, size: 0
```

This is using boost 1.86.0, build with icu 74.2.
