### ISSUE TITLE
Loss of data (C4244) warnings in MSVC 64-bit build

### ISSUE THREAD

**Issue by SpareSimian** [boostorg/locale#42]
Building with MSVC compilers for 64-bit results in several C4244 warnings in api.hpp, due to passing the difference of two pointers (ptrdiff_t) to Win APIs expecting an int. The attached patch adds casts to silence the warnings.

[api.hpp.diff.txt](https://github.com/boostorg/locale/files/3416870/api.hpp.diff.txt)

**Comment by OlafvdSpek** [comment]
C4244 is Loss of data, Loss of precision is a floating point thing.

**Comment by OlafvdSpek** [comment]
Wouldn't a runtime check on size < 4GB be required as well?

**Comment by SpareSimian** [comment]
Issue title corrected, thanks. 

We could certainly put an assert in there to check the size argument. This is really a case of Windows using the wrong type, but it's probably necessary for compatibility. I suggest a test against std::numeric_limits<int>::max(), which would probably get optimized away if int is the same size as ptrdiff_t.

**Comment by Flamefire** [comment]
Fixed by #86
