### ISSUE TITLE
ICU_LINK option does not work anymore

### ISSUE THREAD

**Issue by nenomius** [boostorg/locale#55]
ICU_LINK option does not work now, because `boost.regex` errors build if sees it now.
See https://github.com/boostorg/regex/commit/fc4dc17dc745a9fc4ab1849cef3710354a6b7782 and https://github.com/boostorg/regex/issues/89

I would suggest moving ICU finding/configuration into shared file and using it from there like its done for zlib, bzip2, etc, and not doing the same thing in different ways.

@jzmaddock

**Comment by Flamefire** [comment]
@leha-bot Does this mean you tested #120 already and can confirm it works for you?
