### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Flamefire** [boostorg/locale#69]
With `./b2 toolset=gcc-10 libs/locale/test cxxstd=11 -j4 variant=debug` I see many failing tests with recent ICU

One of those is "USD 1,345.00" instead of "USD1,345.00", other look more confusing.
See https://github.com/Flamefire/locale/runs/3748013166?check_suite_focus=true or https://github.com/Flamefire/locale/actions in general

@artyom-beilis As you wrote the tests I'm not sure if the tests are wrong or the results.

**Comment by artyom-beilis** [comment]
I need to test myself see what happens.

The test is problematic when ICU changes localization. Somethimes it is ICU bug. I'll check

**Comment by artyom-beilis** [comment]
What is ICU version? I can't find in the logs

**Comment by Flamefire** [comment]
On my machine:
```
/** The current ICU library version as a dotted-decimal string. The patchlevel
 *  only appears in this string if it non-zero.
 *  This value will change in the subsequent releases of ICU
 *  @stable ICU 2.4
 */
#define U_ICU_VERSION "66.1"
```

**Comment by Flamefire** [comment]
No wonder the `test_formatting` is failing sometimes. I found this after some refactoring: 
Prior: https://github.com/boostorg/locale/blob/76f6226fb12c900d0cc5c5744c30dc36a36d5b9f/src/boost/locale/icu/formatter.cpp#L255-L263

After: https://github.com/boostorg/locale/blob/6a47ccb02d8176f86b3bfe5448c107c817e5a741/src/boost/locale/icu/formatter.cpp#L258-L266

I.e. if `cache` is given, then it used the "medium" length, otherwise the "full" length, see https://github.com/boostorg/locale/blob/76f6226fb12c900d0cc5c5744c30dc36a36d5b9f/src/boost/locale/icu/predefined_formatters.hpp#L40 Also the fallback `"yyyy-MM-dd HH:mm:ss"` doesn't look like "full" (not sure what that actually is though)

And last but not least I found only 1 callsite of `strftime_to_icu_symbol` and that doesn't pass the `cache` hence it is always unset. So it looks like the cache was forgotten to be passed down after explicitly checking it at https://github.com/boostorg/locale/blob/76f6226fb12c900d0cc5c5744c30dc36a36d5b9f/src/boost/locale/icu/formatter.cpp#L503-L512

@artyom-beilis Do you remember the intended semantics? I struggle to make sense out of that... I'm referring to failures e.g. seen in https://github.com/boostorg/locale/actions/runs/3074715644/jobs/4967667878 

```
Test: %c
Error in line 452: 
---- [1970-02-05 15:33:13] != [Thursday, February 5, 1970 at 3:33:13 PM Greenwich Mean Time]
Test: %x
Error in line 452: 
---- [1970-02-05] != [Feb 5, 1970]
Test: %X
Error in line 452: 
---- [15:33:13] != [3:33:13 PM]
Test: %c
Error in line 452: 
---- [1970-02-05 15:33:13] != [Thursday, February 5, 1970 at 3:33:13 PM Greenwich Mean Time]
Test: %x
Error in line 452: 
---- [1970-02-05] != [Feb 5, 1970]
Test: %X
Error in line 452: 
---- [15:33:13] != [3:33:13 PM]
```
