### ISSUE TITLE
BOOST_LOCALE_HAVE_WCSFTIME_L unused

### ISSUE THREAD

**Issue by Flamefire** [boostorg/locale#88]
The define at https://github.com/boostorg/locale/blob/b889b35645159e7ca9fa7d4e5ef32532fdb1a123/src/posix/numeric.cpp#L35 is not used.

Instead the non-prefixed one is used at https://github.com/boostorg/locale/blob/b889b35645159e7ca9fa7d4e5ef32532fdb1a123/src/posix/numeric.cpp#L125

@artyom-beilis Do you know which test should detect this problem?

**Comment by artyom-beilis** [comment]
Interesting and good question.

This is generic test of `posix_formatting` IIRC.
But it looks like that fallback is working good enough so it wasn't found.
